### ISSUE TITLE
Bug: Cyrillic alphabet is not displayed correctly when exporting Timesheet to PDF

### ISSUE THREAD

**Issue by Lexi4** [jacobtread/obsidian-timekeep#1]
**Describe the bug**
Cyrillic alphabet is not displayed correctly when exporting Timesheet to PDF

**To Reproduce**
1. Make a timekeep block with Cyrillic characters. 
2. Click **Save PDF** suggested by the plugin.
3. Open created PDF file

**Expected behavior**
Both Latin and Cyrillic are supported in result PDF file

**Screenshots**
![image](https://github.com/jacobtread/obsidian-timekeep/assets/5334085/aee784c5-31cf-4d8b-8289-d942f0e36e97)
![image](https://github.com/jacobtread/obsidian-timekeep/assets/5334085/32ab46f1-6e96-4fcf-9613-ed1fbb27c201)

**Additional context**
**Copy Markdown** to a new page, followed by default export PDF in Obsidian works without problems
![image](https://github.com/jacobtread/obsidian-timekeep/assets/5334085/79016752-8cb7-43cd-9773-e7a51c51c63a)

**Comment by jacobtread** [comment]
Hey, the PDF files that are generating correctly are using the font from Obsidian so they have the supported Cyrillic alphabet in the font. However, the timekeep save as pdf is using react-pdf with the Helvetica-Bold font that comes built in

As far as I'm aware its not possible for me to bundle fonts with this plugin so I won't be able to do that (I don't think react-pdf will be able to load it either). I gave an attempt at using a webfont url but it didn't seem to work properly and I'd rather not have the plugin require internet to generate a pdf.

So I'm not going to be able to fix this for you sorry.

In the future this plugin may migrate away from react-pdf and over to https://pdf-lib.js.org/ but for now this doesn't seem like something I'll be able to fix for you

**Comment by jacobtread** [comment]
Re-opened this, I had a play around with it tonight and managed to get custom fonts loaded using esbuild loaders and having them embedded as data urls. 

Got it working using the Roboto font so I've embedded this in the project:
![image](https://github.com/jacobtread/obsidian-timekeep/assets/33708767/7122c6ba-350a-447a-92ce-61304e083e23)

Check out the latest release https://github.com/jacobtread/obsidian-timekeep/releases/tag/1.2.5 for the fix

**Comment by Lexi4** [comment]
Cool! Thanks a lot for the work done and the quick fix ❤️
I will recommend your plugin to my colleagues
