### ISSUE TITLE
Feature: Export duration as decimal

### ISSUE THREAD

**Issue by tmayoff** [jacobtread/obsidian-timekeep#12]
## Is your feature request related to a problem? Please describe.
I want to be able to pull the data into a spreadsheet to process it further. Having the duration be in decimal form would simplify matters a lot

## Describe the solution you'd like
Either a setting for how to export the data when copying to CSV or similar to the setting for the Timestamp display format, have a setting for the duration format

## Describe alternatives you've considered
Some pretty ugly excel formulas, and also the dataviewjs API but this feels like a good addition to the plugin itself

**Comment by jacobtread** [comment]
Sounds good, going to see what I can do around this tonight. Will probabbly go with a drop down setting to pick timestamps or durations.

**Comment by jacobtread** [comment]
Have added a new setting for choosing the duration format for CSV & Markdown (They use the same logic for generating the flat display rows so the formatting logic is linked)

![image](https://github.com/user-attachments/assets/fbbeb35b-56f8-4216-85fe-8748311fbcfb)
