### ISSUE TITLE
JSON FormattingFeature:

### ISSUE THREAD

**Issue by scottrlarson** [jacobtread/obsidian-timekeep#14]
## Is your feature request related to a problem? Please describe.
Somehow, some of my tasks didn't get put into a subEntry. I was going to go into the code to fix it, but the lines are so close togeather and with obsidian text wrapping its very hard to read where each line ends.

## Describe the solution you'd like
Could you make the embed output friendlier by rendering indents and proper line endings? JSON is a nightmare to read as it is.

## Describe alternatives you've considered
Im going to copy the code out into a text editor to make sense of the lines.

**Comment by jacobtread** [comment]
JSON formatting for the copied JSON is now available as an option in the plugin settings in the latest verson
