### ISSUE TITLE
Feature: Allow Setup of New Timer While Current Timer Runs

### ISSUE THREAD

**Issue by julroger2013** [jacobtread/obsidian-timekeep#16]
This is a great update to the original Simple Tracker plugin. I especially like the options for copying the contents of the tracker in different formats, as well as how you've allowed folding up successive portions of the same tracked task (e.g. Task A pt 1, pt 2, pt 3)

Do you suppose you could make it so that you can type in the name of a new task while the timer is still running for the old one, then press the Play/Stop button again to initiate the timer on the new task, while ending the timer on the old one?

There are times that I would like to shift smoothly from task to task, and there's a little friction in needing to first stop the old task before I can type in the details of the new one. It would be great if I could leave the timer running on the old task, type in the new name, and then press start to begin a new timer while also ending the old timer.

**Comment by jacobtread** [comment]
I do not believe it is possible to have the name stick around after stopping the task without storing this in the data JSON which I will not do.

This is a limitation of how obsidian renders the code blocks. The README details this loss of state whenever a mutation occurs (saving/editing/collapsing regions)

I _think_ it may work if you do it in reading mode instead of editing mode? Give it a shot and see if the name sticks around. I think the behavior on there is different in Reader mode as it doesn't loose the state

**Comment by julroger2013** [comment]
I'm not sure if we are talking about the same thing. May I clarify?

What I'm hoping for is that the input box to enter the next block name stays open while the timer is running. The box in the screenshot below:

<img width="386" alt="image" src="https://github.com/user-attachments/assets/ec03e4be-583f-4130-990f-8ca320017469">

Currently, the input box disappears and is replaced with the name of the currently running block, like in this screenshot:

<img width="408" alt="image" src="https://github.com/user-attachments/assets/f1c42513-6f74-4351-9867-f2460d33dfd3">

My idea is (if possible - it might not be, based on what you explained above), whether there could still be an input box available to type in while an old timer is running, so that you can start a new task without first having to stop the old one.

**Comment by julroger2013** [comment]
Oh, and I did try it in Reading Mode. The behavior seemed the same to me.

**Comment by jacobtread** [comment]
Ah yes, I forgot I hid the box while a timer is running. 

My above comments about loss of state will still be true, though in that regard

**Comment by jacobtread** [comment]
If your set of tasks are known ahead of time, you could consider using unstarted tasks with some sort of templating system.

They are mentioned in the README I think or you might have to go through resolced PRs/issues

They're tasks that are already named but have no timing and you just push the start button on them to begin

**Comment by jacobtread** [comment]
> That makes sense. I was hoping the process could be … - Start Timer 1 - Type Name of Timer 2 While Timer 1 Still Runs - Press Start Button Again, Which Will Stop Timer 1 and Start Timer 2 at The Same Time But it sounds like with the code block limitations, it will need to remain … - Start Timer 1 - Stop Timer 1 - Type Name of Timer 2 - Start Timer 2 Did I understand that right? Thank you for taking the time to explain! I figured it wouldn’t hurt to ask. Thank you again!

Yup, I believe that would be only possible if you always used the timekeep from reading mode only. Which is often inconvient. (I'm pretty sure the limitation is only for editing mode but I might be wrong). I think you'd probabbly still loose the state in reading mode though if you scrolled the timer out of view or switched to a different file
