### ISSUE TITLE
UI adjustments

### ISSUE THREAD

**Issue by rk-kontur** [jacobtread/obsidian-timekeep#18]
Hi there,

THANKS for this great plugin. I used SimpeleTimeTracker for a long time but find this much better.

I wonder whether itts possible to implement two changes:

1. Make it possible to adjust Timekeep UI size. By this, I mean: font size, corresponding line height and - most importantly - button size. Ideally, Font and button size could be adjusted and line height would follow.
2. Make it possible to auto-hide details in case the line maximum is not there to guarantee a decent display of data. By this, I mean: 
- Either hide parts of the data inside the startTime and endTime fields in this order: 1 date 2 seconds 3 hours (would be best to display recalculated minutes in this minimal display)
- Alternatively, hide the entire rows for StartTime and endTime and only keep duration. This could also be the last setting for the first bullet point.

I tried adjusting via CSS but could not find any way to achieve the hiding of data progressively. I am, however, a noob in CSS and fiddled mostly with AI prompts.

Again: THANKS for this really cool plugin!!!!

**Comment by jacobtread** [comment]
For 1. Shouldn't be anything stopping you from changing the front size and line height using CSS

For 2. The formatting for start and end date is customizable so you can change that to anything you'd like (Its the "Timestamp display format" in settings). If you'd prefer to hide these you can do so with css by targetting the specific column with something like ':nth-child()' then `display: none` for both the specific `.timekeep-table-head > tr > th` and `.timekeep-row > td` (Using :nth-child to target the column you want to hide)
