### ISSUE TITLE
Feature: i like this plugin very much! Can this plugin be used in Andriod in future?

### ISSUE THREAD

**Issue by toSidian** [jacobtread/obsidian-timekeep#3]

**Comment by jacobtread** [comment]
Unfortunately I don't think it can, I was having issues with certain features on mobile (Around the pdf generation code, and exporting functionality now using electron features which are not available on mobile), It might be possible to get it working on mobile if I disable all the pdf related features on mobile (don't know if I can do that properly though), it's not a planned thing at the moment

**Comment by toSidian** [comment]
> Unfortunately I don't think it can, I was having issues with certain features on mobile (Around the pdf generation code, and exporting functionality now using electron features which are not available on mobile), It might be possible to get it working on mobile if I disable all the pdf related features on mobile (don't know if I can do that properly though), it's not a planned thing at the moment

thank you very much

**Comment by jacobtread** [comment]
I have implemented mobile support in #4 it has been released as [v1.2.10](https://github.com/jacobtread/obsidian-timekeep/releases/tag/1.2.10)

**Comment by toSidian** [comment]
thanks for your contributions! i like it!
