### ISSUE TITLE
Feature:Are there any methods to interact with Dataview？

### ISSUE THREAD

**Issue by PencilMing** [jacobtread/obsidian-timekeep#7]
Are there any methods to interact with Dataview, such as an API for the total duration, which would allow Dataview to read the total time spent on the current file?

**Comment by jacobtread** [comment]
Hey, I have exposed an API for this in #8 I have published this as the latest version, there is an example for using this with Dataview at the bottom of the PR to get the total duration of all timekeep in the file in milliseconds

**Comment by PencilMing** [comment]
That's Great!

**Comment by PencilMing** [comment]
That's Great!
