### ISSUE TITLE
Bug: Broken Obsidian editing and cursor after delete entry confirmation appears

### ISSUE THREAD

**Issue by amerov** [jacobtread/obsidian-timekeep#9]
**Describe the bug**
Broken Obsidian editing and cursor after delete entry confirmation appears

**To Reproduce**

1. start/stop timer
2. edit action
3. delete entry
4. confirm

**Expected behavior**
No broke

**Screenshots**
![image](https://github.com/jacobtread/obsidian-timekeep/assets/196747/45e16446-70ab-455d-8684-69701e138baf)

**Additional context**
OS: Fedora Linux 40

**Comment by jacobtread** [comment]
I think this is a bug around the native browser dialogs, I'll give this a look when I have the chance. There's a temporary fix for this where if you click onto another application/window then back to obsidian it'll work again.

I'll see if maybe using the electron APIs or some workaround to re-focus obsidian will work as a solution

**Comment by jacobtread** [comment]
Yeah, looks to be the native browser dialog is causing this. Have replaced it with an obsidian modal and its not happening anymore. 

Fix is published as v1.4.1
